# Generated by Django 5.2.1 on 2025-05-16 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cor_css', models.CharField(blank=True, max_length=50, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Status de Pedido',
                'verbose_name_plural': 'Status de Pedidos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('payload', models.TextField()),
                ('assinatura', models.CharField(max_length=255, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para identificar este endpoint', max_length=100)),
                ('url', models.URLField(help_text='URL para onde os webhooks serão enviados')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, webhooks não serão enviados para este endpoint')),
                ('auto_enviar', models.BooleanField(default=True, help_text='Se ativado, webhooks serão enviados automaticamente')),
                ('access_token', models.CharField(blank=True, help_text='Token de autenticação opcional para incluir na URL', max_length=255, null=True)),
                ('token_autenticacao', models.CharField(blank=True, help_text='Token de autenticação opcional para incluir nos cabeçalhos de requisição', max_length=255, null=True)),
                ('headers_adicionais', models.TextField(blank=True, help_text="Cabeçalhos adicionais em formato JSON (por exemplo: {'X-Custom': 'Value'})", null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Endpoint de Webhook',
                'verbose_name_plural': 'Configurações de Endpoints de Webhook',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etiqueta_envio', models.URLField(blank=True, null=True)),
                ('metodo_envio', models.IntegerField(blank=True, null=True)),
                ('numero_pedido', models.IntegerField(unique=True)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('documento_cliente', models.CharField(max_length=20)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_destinatario', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=100)),
                ('telefone_destinatario', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('nome_info_adicional', models.CharField(max_length=255)),
                ('telefone_info_adicional', models.CharField(max_length=20)),
                ('email_info_adicional', models.EmailField(max_length=254)),
                ('nome_produto', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('id_sku', models.IntegerField(blank=True, null=True)),
                ('arquivo_pdf_produto', models.URLField(blank=True, null=True)),
                ('design_capa_frente', models.URLField()),
                ('design_capa_verso', models.URLField(blank=True, null=True)),
                ('mockup_capa_frente', models.URLField()),
                ('mockup_capa_costas', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidosMontink.statuspedido')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidosMontink.webhook')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WebhookStatusEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('url_destino', models.URLField()),
                ('payload', models.TextField()),
                ('resposta', models.TextField(blank=True, null=True)),
                ('codigo_http', models.IntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('tentativa_numero', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks_enviados', to='pedidosMontink.pedido')),
            ],
            options={
                'verbose_name': 'Webhook de Status Enviado',
                'verbose_name_plural': 'Webhooks de Status Enviados',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
