# Generated by Django 5.2.1 on 2025-05-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidosMontink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='erro',
            field=models.TextField(blank=True, help_text='Mensagem de erro, se houver', null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='processado',
            field=models.BooleanField(default=False, help_text='Indica se o webhook foi processado com sucesso'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='Código de status HTTP do processamento', null=True),
        ),
    ]
