from .form_serializers import FormularioBaseSerializer
from .zerohum_serializers import ZeroHumSerializer
from .pensi_serializers import PensiSerializer
from .elite_serializers import EliteSerializer
from .coleguium_serializers import coleguiumSerializer