# Generated by Django 5.2.1 on 2025-05-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.IntegerField(blank=True, help_text='ID do webhook que originou este pedido', null=True)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('etiqueta_envio', models.URLField(blank=True, null=True)),
                ('metodo_envio', models.IntegerField(blank=True, null=True)),
                ('numero_pedido', models.IntegerField(unique=True)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('documento_cliente', models.CharField(max_length=20)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('produtos_json', models.TextField(help_text='Lista de produtos em formato JSON')),
                ('endereco_envio_json', models.TextField(help_text='Dados de endereço de envio em formato JSON')),
                ('informacoes_adicionais_json', models.TextField(help_text='Informações adicionais em formato JSON')),
                ('status', models.CharField(default='recebido', help_text='Status atual do pedido', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(help_text='Tipo de evento do webhook', max_length=50)),
                ('payload', models.TextField(help_text='Conteúdo do payload recebido no webhook')),
                ('assinatura', models.CharField(help_text='Assinatura para verificação', max_length=255, null=True)),
                ('verificado', models.BooleanField(default=False, help_text='Indica se o webhook foi verificado com sucesso')),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook Recebido',
                'verbose_name_plural': 'Webhooks Recebidos',
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Chave secreta para validação de assinaturas de webhooks', max_length=255)),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a configuração está ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Webhook',
                'verbose_name_plural': 'Configurações de Webhook',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome para identificar este endpoint', max_length=100)),
                ('url', models.URLField(help_text='URL para onde os webhooks serão enviados')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, webhooks não serão enviados para este endpoint')),
                ('auto_enviar', models.BooleanField(default=True, help_text='Se ativado, webhooks serão enviados automaticamente')),
                ('access_token', models.CharField(blank=True, help_text='Token de autenticação opcional para incluir na URL', max_length=255, null=True)),
                ('token_autenticacao', models.CharField(blank=True, help_text='Token de autenticação opcional para incluir nos cabeçalhos de requisição', max_length=255, null=True)),
                ('headers_adicionais', models.TextField(blank=True, help_text="Cabeçalhos adicionais em formato JSON (por exemplo: {'X-Custom': 'Value'})", null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Endpoint de Webhook',
                'verbose_name_plural': 'Configurações de Endpoints de Webhook',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='WebhookStatusEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.IntegerField(help_text='ID do pedido relacionado a este webhook')),
                ('status', models.CharField(help_text='Status do pedido que gerou o webhook', max_length=50)),
                ('url_destino', models.URLField(help_text='URL para onde o webhook foi enviado')),
                ('payload', models.TextField(help_text='Conteúdo enviado no webhook')),
                ('resposta', models.TextField(blank=True, help_text='Resposta recebida do endpoint', null=True)),
                ('codigo_http', models.IntegerField(blank=True, help_text='Código HTTP da resposta', null=True)),
                ('sucesso', models.BooleanField(default=False, help_text='Indica se o envio foi bem-sucedido')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('tentativa_numero', models.IntegerField(default=1, help_text='Número da tentativa de envio')),
            ],
            options={
                'verbose_name': 'Webhook de Status Enviado',
                'verbose_name_plural': 'Webhooks de Status Enviados',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
