# Generated by Django 5.2.1 on 2025-05-19 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsProducao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Formulário', 'verbose_name_plural': 'Formulários'},
        ),
        migrations.AddField(
            model_name='formulario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que enviou'),
        ),
    ]
