# Generated by Django 5.0.1 on 2025-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsProducao', '0002_alter_formulario_options_formulario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='web_view_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de visualização'),
        ),
    ]
