# Generated by Django 5.2.1 on 2025-05-19 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsProducao', '0003_formulario_web_view_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='unidade_nome',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='unidade_quantidade',
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='formsProducao.formulario', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nome'],
            },
        ),
    ]
