# Generated by Django 5.2.1 on 2025-05-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsProducao', '0004_remove_formulario_unidade_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='nome',
            field=models.CharField(choices=[('ARARUAMA', 'Araruama'), ('CABO_FRIO', 'Cabo Frio'), ('ITABORAI', 'Itaboraí'), ('ITAIPUACU', 'Itaipuaçu'), ('MARICA_I', 'Maricá I'), ('NOVA_FRIBURGO', 'Nova Friburgo'), ('QUEIMADOS', 'Queimados'), ('SEROPEDICA', 'Seropédica'), ('ALCANTARA', 'Alcântara'), ('BANGU', 'Bangu'), ('BARRA_DA_TIJUCA', 'Barra da Tijuca'), ('BELFORD_ROXO', 'Belford Roxo'), ('DUQUE_DE_CAXIAS', 'Duque de Caxias'), ('ICARAI', 'Icaraí'), ('ILHA_DO_GOVERNADOR', 'Ilha do Governador'), ('ITAIPU', 'Itaipu'), ('MADUREIRA', 'Madureira'), ('MEIER', 'Méier'), ('NILOPOLIS', 'Nilópolis'), ('NITEROI', 'Niterói'), ('NOVA_IGUACU', 'Nova Iguaçu'), ('OLARIA', 'Olaria'), ('PRATA', 'Prata'), ('SAO_GONCALO', 'São Gonçalo'), ('SAO_JOAO_DE_MERITI', 'São João de Meriti'), ('VILA_ISABEL', 'Vila Isabel'), ('VILAR_DOS_TELES', 'Vilar dos Teles')], max_length=100, verbose_name='Nome da Unidade'),
        ),
    ]
