# Generated by Django 5.2.1 on 2025-05-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsProducao', '0005_alter_unidade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='capa_pvc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='espiral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='gramatura',
            field=models.CharField(default='75g', max_length=10),
        ),
        migrations.AddField(
            model_name='formulario',
            name='grampos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='papel_adesivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_adesivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
