# Generated by Django 5.2.1 on 2025-05-20 15:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsProducao', '0006_formulario_capa_pvc_formulario_espiral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='json_link',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='link_download',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='web_view_link',
        ),
        migrations.CreateModel(
            name='ArquivoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do arquivo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('link_download', models.URLField(blank=True, max_length=500, null=True)),
                ('web_view_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de visualização')),
                ('json_link', models.URLField(blank=True, max_length=500, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_pdf', to='formsProducao.formulario', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Arquivo PDF',
                'verbose_name_plural': 'Arquivos PDF',
                'ordering': ['-criado_em'],
            },
        ),
    ]
